import { randomUUID } from "node:crypto";
import { closeSync, constants, fsyncSync, lstatSync, mkdirSync, openSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { withCrossProcessFileLock } from "../core/file-lock";
import { resolveProjectPath } from "../core/safe-path";
import { appendWorkflowEvent } from "./journal";
import { createWorkflowEvent } from "./events";
import { markWorkflowOrphaned } from "./ownership";

export const SESSION_LINK_FORMAT_VERSION = 1 as const;
export type WorkflowLinkStatus = "current" | "archived";
export interface NormalSessionLink { readonly kind: "normal"; readonly formatVersion: 1; readonly projectId: string; readonly piSessionId: string; readonly piSessionFile: string; readonly normalModel: string; readonly normalThinking: string; readonly normalTools: readonly string[]; readonly createdAt: string; readonly updatedAt: string }
export interface WorkflowSessionLink { readonly kind: "workflow"; readonly formatVersion: 1; readonly workflowSessionId: string; readonly workflowId: string; readonly activationHash: string; readonly piSessionId: string; readonly piSessionFile: string; readonly normalParentId: string; readonly normalParentFile: string; readonly status: WorkflowLinkStatus; readonly stale: boolean; readonly model: string; readonly thinking: string; readonly tools: readonly string[]; readonly createdAt: string; readonly updatedAt: string; readonly name: string }
export type SessionLink = NormalSessionLink | WorkflowSessionLink;

function linksPath(root: string): string { const resolved = resolveProjectPath(root, ".pi/hive/sessions/session-links-v1.json", { allowMissing: true }); if (!resolved) throw new Error("SESSION_LINK_PATH_INVALID"); return resolved.lexicalPath; }
function freeze<T>(value: T): T { if (value && typeof value === "object") { for (const child of Object.values(value as Record<string, unknown>)) freeze(child); Object.freeze(value); } return value; }
function readLinks(root: string): SessionLink[] { const path = linksPath(root); try { if (lstatSync(path).isSymbolicLink()) throw new Error("SESSION_LINK_PATH_INVALID"); const raw = readFileSync(path, "utf8"); if (Buffer.byteLength(raw) > 1_048_576) throw new Error("SESSION_LINK_LIMIT_EXCEEDED"); const value = JSON.parse(raw) as { formatVersion: number; links: SessionLink[] }; if (value.formatVersion !== 1 || !Array.isArray(value.links)) throw new Error("SESSION_LINK_INVALID"); return value.links; } catch (error: unknown) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw error; } }
function writeLinksUnlocked(root: string, links: readonly SessionLink[]): void { const path = linksPath(root); const dir = dirname(path); mkdirSync(dir, { recursive: true, mode: 0o700 }); const content = `${JSON.stringify({ formatVersion: 1, links })}\n`; if (Buffer.byteLength(content) > 1_048_576) throw new Error("SESSION_LINK_LIMIT_EXCEEDED"); const temp = `${path}.${process.pid}.${randomUUID()}.tmp`; let fd: number | undefined; try { fd = openSync(temp, "wx", 0o600); writeFileSync(fd, content); fsyncSync(fd); closeSync(fd); fd = undefined; renameSync(temp, path); const dirFd = openSync(dir, constants.O_RDONLY); try { fsyncSync(dirFd); } finally { closeSync(dirFd); } } finally { if (fd !== undefined) try { closeSync(fd); } catch { /* best effort */ } try { unlinkSync(temp); } catch { /* published or absent */ } } }
function compareText(a: string, b: string): number { return a < b ? -1 : a > b ? 1 : 0; }
export function listSessionLinks(projectRoot: string): readonly SessionLink[] { return freeze(readLinks(projectRoot).sort((a, b) => (a.kind === b.kind ? (a.kind === "normal" ? compareText(a.piSessionId, (b as NormalSessionLink).piSessionId) : compareText(a.workflowSessionId, (b as WorkflowSessionLink).workflowSessionId)) : a.kind === "normal" ? -1 : 1))); }
function mutateLinks(projectRoot: string, mutate: (links: SessionLink[]) => readonly SessionLink[]): void { const path = linksPath(projectRoot); mkdirSync(dirname(path), { recursive: true, mode: 0o700 }); withCrossProcessFileLock(path, () => writeLinksUnlocked(projectRoot, mutate(readLinks(projectRoot)))); }
export function replaceSessionLinks(projectRoot: string, links: readonly SessionLink[]): void { mutateLinks(projectRoot, () => links); }
export function commitWorkflowSelection(projectRoot: string, workflowId: string, expectedCurrentId: string | undefined, archived: WorkflowSessionLink | undefined, selected: WorkflowSessionLink): void { mutateLinks(projectRoot, (links) => { const latest = links.find((entry): entry is WorkflowSessionLink => entry.kind === "workflow" && entry.workflowId === workflowId && entry.status === "current"); if (latest?.workflowSessionId !== expectedCurrentId) throw new Error("Concurrent workflow selection changed the current session"); return [...links.filter((entry) => entry.kind !== "workflow" || (entry.workflowSessionId !== expectedCurrentId && entry.workflowSessionId !== selected.workflowSessionId)), ...(archived ? [archived] : []), selected]; }); }
export function initializeNormalParent(input: { configured: boolean; projectRoot: string; projectId: string; piSessionId: string; piSessionFile: string; model: string; thinking: string; activeTools: readonly string[] }): { configured: boolean; commands: readonly string[] } { if (!input.configured) return freeze({ configured: false, commands: [] }); const now = new Date().toISOString(); mutateLinks(input.projectRoot, (links) => { const existing = links.find((entry): entry is NormalSessionLink => entry.kind === "normal" && entry.projectId === input.projectId); const normal: NormalSessionLink = freeze({ kind: "normal", formatVersion: 1, projectId: input.projectId, piSessionId: input.piSessionId, piSessionFile: input.piSessionFile, normalModel: input.model, normalThinking: input.thinking, normalTools: [...new Set(input.activeTools)].sort(), createdAt: existing?.createdAt ?? now, updatedAt: now }); return [normal, ...links.filter((entry) => entry.kind !== "normal")]; }); return freeze({ configured: true, commands: ["hive:select", "hive:exit"] }); }
export function upsertWorkflowLink(projectRoot: string, link: WorkflowSessionLink): void { mutateLinks(projectRoot, (links) => [...links.filter((entry) => entry.kind !== "workflow" || entry.workflowSessionId !== link.workflowSessionId), freeze(link)]); }
export function recordWorkflowModelState(projectRoot: string, projectId: string, input: Omit<WorkflowSessionLink, "kind"> | WorkflowSessionLink, model: string, thinking: string, preflight: (model: string, thinking: string) => boolean): WorkflowSessionLink { if (!preflight(model, thinking)) throw new Error("Model/thinking preflight failed"); const now = new Date().toISOString(); const link = freeze({ ...input, kind: "workflow" as const, formatVersion: 1 as const, model, thinking, tools: [...input.tools].sort(), updatedAt: now }); upsertWorkflowLink(projectRoot, link); appendWorkflowEvent(projectRoot, createWorkflowEvent({ projectId, sessionId: link.workflowSessionId, type: "session.selected", payload: { model, thinking }, producer: "runtime" })); return link; }
export function markMissingPiSession(projectRoot: string, projectId: string, workflowSessionId: string): void { markWorkflowOrphaned(projectRoot, workflowSessionId, projectId, "linked Pi session is missing"); }
