import type { ExtensionContext } from "@earendil-works/pi-coding-agent";
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { homedir } from "node:os";
import type { HiveState, SkillRegistryEntry } from "../core/types";
import { ensureDir, readIfSmall, safeRead, slug } from "../core/utils";
import { parseFrontmatter } from "../core/yaml";

const PROJECT_SKILL_ROOTS = [
  "skills",
  ".pi/skills",
  ".agents/skills",
  ".agent/skills",
  ".atl/skills",
  ".claude/skills",
  ".gemini/skills",
  ".cursor/skills",
  ".github/skills",
  ".codex/skills",
  ".qwen/skills",
  ".kiro/skills",
  ".openclaw/skills",
];

const USER_SKILL_ROOTS = [
  "~/.pi/agent/skills",
  "~/.agents/skills",
  "~/.config/agents/skills",
  "~/.claude/skills",
  "~/.gemini/skills",
  "~/.cursor/skills",
  "~/.codex/skills",
  "~/.qwen/skills",
  "~/.kiro/skills",
  "~/.openclaw/skills",
];

function expandHome(path: string): string {
  return path.startsWith("~/") ? join(homedir(), path.slice(2)) : path;
}

function walkSkillFiles(root: string, maxDepth = 5): string[] {
  const out: string[] = [];
  const visit = (dir: string, depth: number) => {
    if (depth > maxDepth) return;
    let entries: ReturnType<typeof readdirSync> = [];
    try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      if (["node_modules", ".git", "dist", "build", "coverage"].includes(entry.name)) continue;
      const full = join(dir, entry.name);
      if (entry.isDirectory()) visit(full, depth + 1);
      else if (entry.isFile() && entry.name === "SKILL.md") out.push(full);
    }
  };
  visit(root, 0);
  return out;
}

function firstParagraph(body: string): string {
  return body
    .split(/\n\s*\n/)
    .map((part) => part.replace(/\s+/g, " ").trim())
    .find(Boolean) || "";
}

function rootPaths(ctx: ExtensionContext): Array<{ root: string; scope: "project" | "user" }> {
  const project = PROJECT_SKILL_ROOTS.map((p) => ({ root: join(ctx.cwd, p), scope: "project" as const }));
  const user = USER_SKILL_ROOTS.map((p) => ({ root: expandHome(p), scope: "user" as const }));
  return [...project, ...user];
}

export function discoverSkillRegistry(ctx: ExtensionContext): SkillRegistryEntry[] {
  const entries: SkillRegistryEntry[] = [];
  const seen = new Set<string>();
  for (const { root, scope } of rootPaths(ctx)) {
    if (!existsSync(root)) continue;
    for (const file of walkSkillFiles(root)) {
      let parsed: ReturnType<typeof parseFrontmatter>;
      try { parsed = parseFrontmatter(safeRead(file)); } catch { continue; }
      const name = String(parsed.attrs.name || dirname(file).split(/[\\/]/).pop() || "skill").trim();
      const description = String(parsed.attrs.description || firstParagraph(parsed.body) || "No description.").trim();
      const key = `${scope}:${slug(name)}:${file}`;
      if (seen.has(key)) continue;
      seen.add(key);
      entries.push({ name, path: file, description, scope, useWhen: description });
    }
  }
  return entries.sort((a, b) => a.scope.localeCompare(b.scope) || a.name.localeCompare(b.name));
}

export function registryPath(ctx: ExtensionContext): string {
  return join(ctx.cwd, ".atl", "hive-skill-registry.md");
}

export function writeSkillRegistry(ctx: ExtensionContext, entries: SkillRegistryEntry[]): string {
  const outPath = registryPath(ctx);
  ensureDir(dirname(outPath));
  const lines = [
    "# Hive skill registry",
    "",
    "Generated by pi-hive. It indexes project/user SKILL.md files so hive agents can discover procedures without inlining every skill body.",
    "",
    `Generated: ${new Date().toISOString()}`,
    "",
    "| Scope | Skill | Path | Description |",
    "|---|---|---|---|",
    ...entries.map((entry) => {
      const displayPath = entry.path.startsWith(ctx.cwd) ? relative(ctx.cwd, entry.path) : entry.path.replace(homedir(), "~");
      const desc = entry.description.replace(/\|/g, "\\|").slice(0, 240);
      return `| ${entry.scope} | ${entry.name} | \`${displayPath}\` | ${desc} |`;
    }),
    "",
  ];
  writeFileSync(outPath, lines.join("\n"));
  return outPath;
}

export function refreshSkillRegistry(state: HiveState, ctx: ExtensionContext): { entries: SkillRegistryEntry[]; path: string; missingConfigured: string[] } {
  const entries = discoverSkillRegistry(ctx);
  state.skillRegistry = entries;
  const path = writeSkillRegistry(ctx, entries);
  const missingConfigured: string[] = [];
  for (const runtime of state.runtimes.values()) {
    for (const ref of runtime.config.skills || []) {
      if (!readIfSmall(ref.path.startsWith("/") ? ref.path : join(ctx.cwd, ref.path), 1_000_000)) missingConfigured.push(`${runtime.config.name}: ${ref.path}`);
    }
  }
  return { entries, path, missingConfigured };
}

export function findRegisteredSkill(state: HiveState, name: string): SkillRegistryEntry | undefined {
  const wanted = slug(name);
  return state.skillRegistry.find((entry) => slug(entry.name) === wanted || slug(entry.path.replace(/^.*[\\/]/, "").replace(/\.md$/, "")) === wanted);
}

export function renderSkillRegistryMenu(state: HiveState, limit = 40): string {
  if (!state.skillRegistry.length) return "## Discovered project/user skills\nNo registry entries discovered yet.";
  const rows = state.skillRegistry.slice(0, limit).map((entry) => {
    const display = entry.path.replace(homedir(), "~");
    return `- ${entry.name} (${entry.scope}): ${entry.description.slice(0, 160)} — ${display}`;
  });
  const more = state.skillRegistry.length > limit ? `\n- ... ${state.skillRegistry.length - limit} more in .atl/hive-skill-registry.md` : "";
  return `## Discovered project/user skills\nThese are available via load_skill by name when relevant. Prefer explicitly configured skills first.\n${rows.join("\n")}${more}`;
}
